### ISSUE TITLE
Failed to parse package.json data

### ISSUE THREAD

**Issue by rubystar** [napcs/node-livereload#27] opened 2014-10-26 10:25 UTC
I was trying to:

```
sudo npm install -g livereload
```
and got:

```
Failed to parse json
npm ERR! Unexpected end of input
npm ERR! File: /home/venkat/.npm/commander/0.6.1/package/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! System Linux 3.13.0-38-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "livereload"
npm ERR! cwd /home/venkat
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! file /home/venkat/.npm/commander/0.6.1/package/package.json
npm ERR! code EJSONPARSE
npm http 304 http://registry.npmjs.org/ms/0.6.2
npm http 304 http://registry.npmjs.org/options
npm http 304 http://registry.npmjs.org/tinycolor
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/venkat/npm-debug.log
npm ERR! not ok code 0
```

I am using
```
Ubuntu 14.04.1 LTS
node v0.10.25
npm 1.3.10
```

Thanks in advance!

**Comment by napcs** [comment] 2015-01-09 21:51
Blargh. Thanks. Will be fixed shortly.

**Comment by napcs** [comment] 2015-01-14 22:09
Cannot reproduce. Works as expected from here.

**Closed by napcs** 2015-01-14 22:09 UTC

**Comment by rubystar** [comment] 2015-01-19 06:45
sorry i was on holidays and couldn't respond on time. I'll check again and revert. Thanks!
