### ISSUE TITLE
Error: not opened in WebSocket.js

### ISSUE THREAD

**Issue by foxx** [napcs/node-livereload#37] opened 2015-05-06 13:31 UTC
Every now and then I get the following error in LiveReload.

```
info: livereload: Sending refresh to browser
/tmp/tmp.vYah8haBMV/livereload/node_modules/websocket.io/node_modules/ws/lib/WebSocket.js:175
    else throw new Error('not opened');
               ^
Error: not opened
    at WebSocket.send (/tmp/tmp.vYah8haBMV/livereload/node_modules/websocket.io/node_modules/ws/lib/WebSocket.js:175:16)
    at WebSocket.write (/tmp/tmp.vYah8haBMV/livereload/node_modules/websocket.io/lib/protocols/hybi.js:101:13)
    at WebSocket.Socket.send (/tmp/tmp.vYah8haBMV/livereload/node_modules/websocket.io/lib/socket.js:106:8)
    at Server.refresh (/tmp/tmp.vYah8haBMV/livereload/lib/livereload.js:179:30)
```

**Comment by napcs** [comment] 2015-08-14 01:57
I have not been able to recreate this. Any more info you can provide?

**Comment by napcs** [comment] 2015-09-22 19:59
Closing - cannot reproduce and no further followup. Reopen if needed.

**Closed by napcs** 2015-09-22 19:59 UTC
