### ISSUE TITLE
does not work with absolute paths

### ISSUE THREAD

**Issue by ORESoftware** [napcs/node-livereload#91] opened 2017-03-03 20:48 UTC
```bash
./node_modules/.bin/livereload  public # relative path works
./node_modules/.bin/livereload  /foo/bar/baz/public # absolute path does not work
```

absolute paths don't seem to work here, is my observation correct? 
My assumption is that you are not checking if the path is absolute before appending the current working directory.

Please do something like this:

```js
const path = require('path');

function resolve(p){
  return path.isAbsolute(p) ? p : path.resolve(process.cwd() + '/' + p)
}

```

**Comment by napcs** [comment] 2017-03-07 03:35
Hey, would you please use the issue template next time you report an issue? It'd really help me out.

As for this particular issue, I'm not inclined to make this adjustment right now. I'm struggling to see the use case for it - the project is 4+ years old and this is the first time this has come up. I'd welcome any insight into your current situation.

**Comment by napcs** [comment] 2017-03-09 17:38
@ORESoftware 

Just tested this using the `-d` flag to debug:

```
livereload /Users/brianhogan/tmp/pages -d
```

Results:

```
Handshaking with client using protocol 7...

Client message: {"command":"info","plugins":{"less":{"disable":false,"version":"1.0"}},"url":"file:///Users/brianhogan/tmp/pages/index.html"}

Reloading: /Users/brianhogan/tmp/pages/index.html

Client closed connection

Browser connected.

Client message: {"command":"hello","protocols":["http://livereload.com/protocols/official-6","http://livereload.com/protocols/official-7"],"ver":"2.2.2","snipver":1}

Client requested handshake...

Handshaking with client using protocol 7...

Client message: {"command":"info","plugins":{"less":{"disable":false,"version":"1.0"}},"url":"file:///Users/brianhogan/tmp/pages/index.html"}
```

Seems like it's working as expected.  We do resolve the paths from absolute to full paths, no matter how they run. We treat everything as relative.

Closing as can't reproduce. But reopen if you can provide more details.

**Closed by napcs** 2017-03-09 17:38 UTC
