### ISSUE TITLE
Saving .less files doesn't reload tab

### ISSUE THREAD

**Issue by Costegillio** [napcs/node-livereload#133] opened 2019-09-07 08:33 UTC
## What version of Livereload are you using?

0.8.0.

## What OS are you using?

Windows 8.1 Pro x64.

## What web browser are you using? (Browser name and specific version please)

Chrome 76.0.3809.132 64bit.

## Expected result

Reload .less files after saving changes.

## Actual result

.php and .html files reloads fine but saving changes in .less files doesn't reload tab.

## Steps to reproduce issue 

Run these command in command line: 

> D:\domains\admin>livereload . -ee 'less' -d

Further see message what less plugin is disabled:

> Client message: {"command":"info","plugins":{"less":{"disable":true,"version":"1.0"}},"url":"http://admin/"}

## Full debug info

> D:\domains\admin>livereload . -ee 'less' -d
> LiveReload is waiting for a browser to connect...
> 
> Protocol version: 7
> Exclusions: /\.git\//,/\.svn\//,/\.hg\//
> Extensions: 'less',html,css,js,png,gif,jpg,php,php5,py,rb,erb,coffee
> Polling: false
> 
> 
> Starting LiveReload v0.8.0 for D:\domains\admin on port 35729.
> Watching D:\domains\admin...
> 
> Browser connected.
> 
> Client message: {"command":"hello","protocols":["http://livereload.com/protocols/official-6","http://livereload.com/protocols/official-7"],"ver":"3.0.0","ext":"Chrome","extver":"2.1.0"}
> 
> Client requested handshake...
> 
> Handshaking with client using protocol 7...
> 
> Client message: {"command":"info","plugins":{"less":{"disable":true,"version":"1.0"}},"url":"http://admin/"}
>

**Comment by sebbi08** [comment] 2019-09-10 09:40
i think the problem is not that the page wont get reload but more that the new url that gets inserted is cache busted and therefor the new syle is added on top of the exising one but with lower priority.

Initial Page load :
![image](https://user-images.githubusercontent.com/9070136/64602789-a7dcf200-d3bf-11e9-8909-d29804f9a216.png)


After change in less file:
![image](https://user-images.githubusercontent.com/9070136/64602839-bf1bdf80-d3bf-11e9-8b46-0b36e4445c61.png)

as you can see the new css is inserted above the old one

**Comment by napcs** [comment] 2019-09-17 20:26
@Costegillio I am not seeing the full picture here. The `livereload` CLI doesn't do anything at all with the actual body of the page. It just sends a JSON message to the client.  

What Livereload client are you using?

**Comment by napcs** [comment] 2019-10-04 16:11
I'm closing this. I don't have enough data to understand if this is indeed an issue with this library and not another thing that builds on this library. If I'm wrong, please reopen.

**Closed by napcs** 2019-10-04 16:11 UTC
