### ISSUE TITLE
Arrays of Extensions Not Accepted as per Documentation

### ISSUE THREAD

**Issue by F1LT3R** [napcs/node-livereload#89] opened 2017-02-13 21:56 UTC
## What version are you using? (Don't say latest. Be specific.)
0.6.0

## Expected result

The README says
> "`exts` is an array of extensions you want to observe. "

https://github.com/napcs/node-livereload/blame/master/README.md#L156

Example:

```javascript
const ary = [
    '.md',
    '.text'
];

const liveReloadServer = liveReload.createServer({
	port: 35729,
        exts: ary
}).watch(list);
```

## Actual result

Nothing happens when you pass an array, you have to pass a string.

Example:

```javascript
const ary = [
    '.md',
    '.text'
];

const liveReloadServer = liveReload.createServer({
	port: 35729,
        exts: ary.join(' ')
}).watch(list);
```

## Steps to reproduce issue

Use the code above.

## Why is this important?

Docs are confusing. The JavaScript  part of the API could be more JavaScript~y.

**Comment by napcs** [comment] 2017-02-17 21:06
Ugh. Thanks - that whole bit is gross and needs to be cleaned up.

**Comment by napcs** [comment] 2017-03-09 16:33
@F1LT3R I tested this with the following:

```
var liveReload = require(livereload');

const ary = [
    'md',
    'text'
];

const liveReloadServer = liveReload.createServer({
	port: 35729,
  debug: true,
        exts: ary
}).watch(__dirname);
```

Note that my array of extensions to watch do not include the leading period.

The code works as expected:

```
Refresh: /Users/brianhogan/dev/oss/node-livereload/README.md
```

Closing as "can't reproduce"

**Closed by napcs** 2017-03-09 16:33 UTC
Labels: bug

**Comment by farism** [comment] 2017-03-19 07:31
@napcs How do you feel about replacing the exts rather than concat'ing with the defaults? Though, I suppose you could achieve something similar with `exclusions`. It just seems like unexpected behavior to me.

**Comment by napcs** [comment] 2017-03-20 01:50
@farism yea... it's been that way since before I took over the project. I agree it's weird behavior though. I'm open to ideas.
