### ISSUE TITLE
LiveReload 0.7.0 says reloading but doesn't

### ISSUE THREAD

**Issue by DarkVamprism** [napcs/node-livereload#128] opened 2019-04-05 09:55 UTC
## What version of Livereload are you using?

v0.7.0

## What OS are you using?

Windows 10

## What web browser are you using? (Browser name and specific version please)
Tried in Chrome and Firefox both have same issue

## Expected result
LiveReload should trigger on the page

## Actual result
The livereload console says "Reloading: " etc but the page does not reload(using the sublime text livereload works so it isnt the browser)

## Steps to reproduce issue 
Run Commands
```
npm i -g livereload
livereload .
```

**Comment by napcs** [comment] 2019-04-24 17:20
@DarkVamprism Hi. One more piece of info I need - Are you using the LiveReload browser extension, or did you insert the JS from the file as shown in the README?

**Comment by DarkVamprism** [comment] 2019-04-25 04:02
I tried both and neither worked.

**Comment by napcs** [comment] 2019-05-02 00:36
Thanks for the additional info. I'll see what I can find.

**Comment by napcs** [comment] 2019-05-26 14:46
@DarkVamprism I release 0.8.0 which has updated file watching deps. Can you let me know if you're still having problems?

**Comment by cmacdonnacha** [comment] 2019-05-29 11:01
I just tried version 0.8.0 and see the same issue. The files say "Reloading" but the browser does no automatically refresh.

**Comment by napcs** [comment] 2019-05-30 19:14
@cmacdonnacha You've set the client to use the same port number? Are you using the browser extension or embedded JS?

I cannot reproduce this issue on Chrome or Firefox on Windows 10 with Node.js 10 LTS. Any more information you can provide would be great. Here's a quick cast of my test on  Windows 10.

![windows10](https://user-images.githubusercontent.com/1306/58657914-ec4af300-82e4-11e9-9253-5349f43217ea.gif)

**Comment by napcs** [comment] 2019-06-05 19:43
@DarkVamprism I'm not able to reproduce this on a couple of windows machines now. Is there any additional info you can give about your setup?

**Comment by DarkVamprism** [comment] 2019-06-06 12:08
I am not sure if cmacdonnacha has the same issue but seeing your gif helped me see what was supposed to happen. I re-setup the project and had the same issue but noticed I wasn't getting the "Browser connected" message so I tried closing my sublime text editor and restarted the webpage and it connected.

It turns out that even though the liveReload plugin for sublime was set to disabled, it still had the server running and it caught the client preventing this plugin from being able to listen.

**Comment by napcs** [comment] 2019-06-06 14:29
@DarkVamprism ah yea that makes sense. Great. Closing this issue.

**Closed by napcs** 2019-06-06 14:29 UTC
